# Generated by Django 4.2 on 2024-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="picture1",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="picture2",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="picture3",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="picture4",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="picture5",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
    ]
