# Generated by Django 4.2 on 2024-04-09 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_remove_listing_location_listing_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="saller",
            new_name="seller",
        ),
    ]
